### ISSUE TITLE
Outdated `numpy` dependency

### ISSUE THREAD

**Issue by TheoCGaming** [idkman2021/BigOuncesAudioEffects#10]
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/theocgaming/Programs/beat-manipulator/beatman.py", line 43, in <module>
    bm.beatswap(audio=inp, output=output, pattern=pattern, scale = scale, shift = shift)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 518, in beatswap
    if not isinstance(audio, song): audio = song(audio = audio, sr = sr, log = log)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 16, in __init__
    self.audio, self.sr = io._load(audio=audio, sr=sr)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/io.py", line 105, in _load
    if isinstance(audio, str): return(open_audio(path=audio, lib=lib))
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/io.py", line 55, in open_audio
    audio,sr=open_audio(path, i)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/io.py", line 40, in open_audio
    import madmom
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/__init__.py", line 23, in <module>
    from . import audio, evaluation, features, io, ml, models, processors, utils
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/__init__.py", line 285, in <module>
    from . import beats, chords, downbeats, key, notes, onsets, tempo
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/downbeats.py", line 18, in <module>
    from .beats_hmm import (BarStateSpace, BarTransitionModel,
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/beats_hmm.py", line 19, in <module>
    from madmom.ml.hmm import ObservationModel, TransitionModel
open_audio with madmom: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
Analyzing beats using madmom.BeatDetectionProcessor; beatmap hasn't been generated yet. Generating...

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/theocgaming/Programs/beat-manipulator/beatman.py", line 43, in <module>
    bm.beatswap(audio=inp, output=output, pattern=pattern, scale = scale, shift = shift)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 525, in beatswap
    audio.beatswap(pattern = pattern, scale = scale, shift = shift, length = length)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 163, in beatswap
    if self.beatmap is None: self.beatmap_generate()
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 128, in beatmap_generate
    self.beatmap = beatmap.generate(audio = self.audio, sr = self.sr, lib=lib, caching=caching, filename = self.path, log = self.log, load_settings = load_settings)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/beatmap.py", line 83, in generate
    import madmom
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/__init__.py", line 23, in <module>
    from . import audio, evaluation, features, io, ml, models, processors, utils
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/__init__.py", line 285, in <module>
    from . import beats, chords, downbeats, key, notes, onsets, tempo
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/downbeats.py", line 18, in <module>
    from .beats_hmm import (BarStateSpace, BarTransitionModel,
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/beats_hmm.py", line 19, in <module>
    from madmom.ml.hmm import ObservationModel, TransitionModel
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/theocgaming/Programs/beat-manipulator/beatman.py", line 43, in <module>
    bm.beatswap(audio=inp, output=output, pattern=pattern, scale = scale, shift = shift)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 525, in beatswap
    audio.beatswap(pattern = pattern, scale = scale, shift = shift, length = length)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 163, in beatswap
    if self.beatmap is None: self.beatmap_generate()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 128, in beatmap_generate
    self.beatmap = beatmap.generate(audio = self.audio, sr = self.sr, lib=lib, caching=caching, filename = self.path, log = self.log, load_settings = load_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/beatmap.py", line 83, in generate
    import madmom
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/__init__.py", line 23, in <module>
    from . import audio, evaluation, features, io, ml, models, processors, utils
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/__init__.py", line 285, in <module>
    from . import beats, chords, downbeats, key, notes, onsets, tempo
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/downbeats.py", line 18, in <module>
    from .beats_hmm import (BarStateSpace, BarTransitionModel,
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/beats_hmm.py", line 19, in <module>
    from madmom.ml.hmm import ObservationModel, TransitionModel
  File "madmom/ml/hmm.pyx", line 1, in init madmom.ml.hmm
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

gotta love the console spam

**Comment by TheoCGaming** [comment]
shit i think it's upstream with madmom

**Comment by TheoCGaming** [comment]
after running `ruff check ~/.local/lib/python3.12/site-packages/madmom/*/*.py --select NPY201 --fix` (stupid, yes) it gave me 

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/theocgaming/Programs/beat-manipulator/beatman.py", line 43, in <module>
    bm.beatswap(audio=inp, output=output, pattern=pattern, scale = scale, shift = shift)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 518, in beatswap
    if not isinstance(audio, song): audio = song(audio = audio, sr = sr, log = log)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 16, in __init__
    self.audio, self.sr = io._load(audio=audio, sr=sr)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/io.py", line 105, in _load
    if isinstance(audio, str): return(open_audio(path=audio, lib=lib))
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/io.py", line 55, in open_audio
    audio,sr=open_audio(path, i)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/io.py", line 40, in open_audio
    import madmom
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/__init__.py", line 23, in <module>
    from . import audio, evaluation, features, io, ml, models, processors, utils
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/__init__.py", line 285, in <module>
    from . import beats, chords, downbeats, key, notes, onsets, tempo
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/downbeats.py", line 18, in <module>
    from .beats_hmm import (BarStateSpace, BarTransitionModel,
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/beats_hmm.py", line 19, in <module>
    from madmom.ml.hmm import ObservationModel, TransitionModel
open_audio with madmom: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
Analyzing beats using madmom.BeatDetectionProcessor; beatmap hasn't been generated yet. Generating...

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/theocgaming/Programs/beat-manipulator/beatman.py", line 43, in <module>
    bm.beatswap(audio=inp, output=output, pattern=pattern, scale = scale, shift = shift)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 525, in beatswap
    audio.beatswap(pattern = pattern, scale = scale, shift = shift, length = length)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 163, in beatswap
    if self.beatmap is None: self.beatmap_generate()
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 128, in beatmap_generate
    self.beatmap = beatmap.generate(audio = self.audio, sr = self.sr, lib=lib, caching=caching, filename = self.path, log = self.log, load_settings = load_settings)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/beatmap.py", line 83, in generate
    import madmom
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/__init__.py", line 23, in <module>
    from . import audio, evaluation, features, io, ml, models, processors, utils
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/__init__.py", line 285, in <module>
    from . import beats, chords, downbeats, key, notes, onsets, tempo
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/downbeats.py", line 18, in <module>
    from .beats_hmm import (BarStateSpace, BarTransitionModel,
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/beats_hmm.py", line 19, in <module>
    from madmom.ml.hmm import ObservationModel, TransitionModel
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/theocgaming/Programs/beat-manipulator/beatman.py", line 43, in <module>
    bm.beatswap(audio=inp, output=output, pattern=pattern, scale = scale, shift = shift)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 525, in beatswap
    audio.beatswap(pattern = pattern, scale = scale, shift = shift, length = length)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 163, in beatswap
    if self.beatmap is None: self.beatmap_generate()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 128, in beatmap_generate
    self.beatmap = beatmap.generate(audio = self.audio, sr = self.sr, lib=lib, caching=caching, filename = self.path, log = self.log, load_settings = load_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/beatmap.py", line 83, in generate
    import madmom
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/__init__.py", line 23, in <module>
    from . import audio, evaluation, features, io, ml, models, processors, utils
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/__init__.py", line 285, in <module>
    from . import beats, chords, downbeats, key, notes, onsets, tempo
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/downbeats.py", line 18, in <module>
    from .beats_hmm import (BarStateSpace, BarTransitionModel,
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/features/beats_hmm.py", line 19, in <module>
    from madmom.ml.hmm import ObservationModel, TransitionModel
  File "madmom/ml/hmm.pyx", line 1, in init madmom.ml.hmm
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

**Comment by TheoCGaming** [comment]
it looks like there are other problems `ruff` didn't pick up on

**Comment by TheoCGaming** [comment]
what
the fuck

`madmom/ml/hmm.pyx` doesn't exist

not in BeatManipulator, nor in madmom.

**Comment by inikishev** [comment]
> TheoCGaming

yeah i think its madmom but i actually havent been able to run this on python higher than 3.10 but that was like half a year ago and then they made numpy 2 and i havent tried it since, but they also updated madmom 10 month ago, and i installed it earlier so maybe thats why i havent had issues

**Comment by inikishev** [comment]
I will also say the way beat-manipulator is coded is pretty dumb and I cant add new effects that I want to add and the code is too hard to change, and and I know how to make it better but Haven't bothered yet because its a lot of code ,and then I will be less lazy about adding docker and it will work forever

**Comment by inikishev** [comment]
Ima close this for now as it seems to work with numpy <2, but if this doesn't work at all, lmk
