### ISSUE TITLE
this is what happens when you use an old version of madmom

### ISSUE THREAD

**Issue by TheoCGaming** [idkman2021/BigOuncesAudioEffects#9]
`python3 -m beatman -i "/home/theocgaming/Music/dubioza kolektiv/3.mp3" -o "output/fukt.mp3" -p "1, 4, 3, 2" -s 1.5`
spits out
```
open_audio with madmom: cannot import name 'MutableSequence' from 'collections' (/usr/lib/python3.12/collections/__init__.py)
Analyzing beats using madmom.BeatDetectionProcessor; beatmap hasn't been generated yet. Generating...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/theocgaming/Programs/beat-manipulator/beatman.py", line 43, in <module>
    bm.beatswap(audio=inp, output=output, pattern=pattern, scale = scale, shift = shift)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 525, in beatswap
    audio.beatswap(pattern = pattern, scale = scale, shift = shift, length = length)
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 163, in beatswap
    if self.beatmap is None: self.beatmap_generate()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/main.py", line 128, in beatmap_generate
    self.beatmap = beatmap.generate(audio = self.audio, sr = self.sr, lib=lib, caching=caching, filename = self.path, log = self.log, load_settings = load_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/theocgaming/Programs/beat-manipulator/beat_manipulator/beatmap.py", line 83, in generate
    import madmom
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/__init__.py", line 24, in <module>
    from . import audio, evaluation, features, io, ml, models, processors, utils
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/audio/__init__.py", line 27, in <module>
    from . import comb_filters, filters, signal, spectrogram, stft
  File "madmom/audio/comb_filters.pyx", line 15, in init madmom.audio.comb_filters
  File "/home/theocgaming/.local/lib/python3.12/site-packages/madmom/processors.py", line 23, in <module>
    from collections import MutableSequence
ImportError: cannot import name 'MutableSequence' from 'collections' (/usr/lib/python3.12/collections/__init__.py)
```

**Comment by TheoCGaming** [comment]
numpy also complained:

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
```

**Comment by TheoCGaming** [comment]
yes, it was user error (i was stupid and used an old version of madmom)
